### ISSUE TITLE
can't open it

### ISSUE THREAD

**Issue by BearJean** [aitjcize/cppman#80]
```
Traceback (most recent call last):
  File "/usr/local/bin/cppman", line 40, in <module>
    from cppman.main import Cppman
  File "/usr/local/lib/python2.7/dist-packages/cppman/main.py", line 33, in <module>
    import urllib.request
ImportError: No module named request
```
can you tell me how to solve this problem?
I try:
```
sudo pip install urllib
pip install urllib
sudo pip install request
pip install request
```
and when I try type"import urllib“and"inport request"in the python command Interpreter，the result is true.

**Comment by createwindow** [comment]
i met the same problem like you, have u solved it?

**Comment by BearJean** [comment]
I try pip3,still can't let it done

**Comment by deibit** [comment]
```
pip uninstall mancpp
pip3 install mancpp
```
It worked for me on MacOS

**Comment by aitjcize** [comment]
Correct, cppman is written in python3, you seemed to be using python2.
